Issue 1 Create an Entry
AddyAbid/code-journal pull request #5
Opened 2021-09-08 23:48 UTC by AddyAbid

https://user-images.githubusercontent.com/85080021/132600056-db38f6f3-a5a9-436b-b8ea-f368c6583197.mp4

2021-09-08 23:59 UTC, codingcodymiller requested changes

2021-09-08 23:59 UTC, codingcodymiller commented on index.html
> +    </div>
Your indentation seemed to get kinda messed up here, please revise. Doubler check that you ran `npm ci` in your repo, too

2021-09-08 23:59 UTC, codingcodymiller commented on index.html
> +    </div>
Only this portion should be a child of the `header` element, the rest of the HTML for the form content should be in the `main` element.

2021-09-08 23:59 UTC, codingcodymiller commented on js/main.js
> +  if (event.target) {
Why `if(event.target)`? If this is an event handler, that should always have a truth value. What you really want to check is if the input for the URL has a value. If there is no value inside it, you should set the `src` to the placeholder image, but if there is a value, use that as the new `src`

2021-09-08 23:59 UTC, codingcodymiller commented on js/main.js
> +  $imgSource.src = placeholderImagePath;
I would use `setAttribute` rather than assigning directly to the `src` property like this.

2021-09-08 23:59 UTC, codingcodymiller commented on js/main.js
> +  return formValues;
There won't be any `return` necessary here.

2021-09-08 23:59 UTC, codingcodymiller commented on js/main.js
> +});
This code should be in `data.js`. You want the localStorage code to be in the same file as the data model it is preserving.

2021-09-08 23:59 UTC, codingcodymiller commented on js/main.js
> +  data.entries = JSON.parse(lastInput);
This is incorrect, you should be replacing the value of `data` entirely with the object you parsed from `localStorage`.

2021-09-09 00:21 UTC, AddyAbid commented
https://user-images.githubusercontent.com/85080021/132602463-d40ea4d2-f691-4ba0-b527-ccec8bcd416d.mp4

2021-09-09 00:25 UTC, codingcodymiller requested changes

2021-09-09 00:25 UTC, codingcodymiller commented on js/main.js
> +  if ($imgInput !== '') {
`$imgInput` is the element itself, it will never be an empty string. You need to check `$imgInput.value`

2021-09-09 00:25 UTC, codingcodymiller commented on js/main.js
> +  return changeImage;
No return is necessary, this is an event handler.

2021-09-09 00:29 UTC, AddyAbid commented
https://user-images.githubusercontent.com/85080021/132603020-44417e53-37af-48b2-82bf-f982d1c25a47.mp4

2021-09-09 00:39 UTC, codingcodymiller approved these changes

2021-09-09 00:42 UTC, merged